# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
